# Freetype GL - A C OpenGL Freetype engine
#
# Distributed under the OSI-approved BSD 2-Clause License.  See accompanying
# file `LICENSE` for more details.
version: ci-{build}

environment:
  matrix:

  # Windows CMake + MSVC
  - job_name: CMake

  # Windows MSVS + MSVC
  - job_name: MSVS_Debug_x64
    job_group: MSVS
    appveyor_build_worker_image: Visual Studio 2019
    configuration: Debug
    platform: x64

  - job_name: MSVS_Debug_x86
    job_group: MSVS
    appveyor_build_worker_image: Visual Studio 2019
    configuration: Debug
    platform: x86

  - job_name: MSVS_Release_x64
    job_group: MSVS
    appveyor_build_worker_image: Visual Studio 2019
    configuration: Release
    platform: x64

  - job_name: MSVS_Release_x86
    job_group: MSVS
    appveyor_build_worker_image: Visual Studio 2019
    configuration: Release
    platform: x86

matrix:
  fast_finish: true

init:
  - git config --global core.eol native
  - git config --global core.autocrlf true

for:

  -
    matrix:
      only:
        - job_name: Cmake
    install:
    - '"C:\Program Files (X86)\Microsoft Visual Studio 12.0\VC\vcvarsall.bat"'
    # Remove the VS Xamarin targets to reduce AppVeyor specific noise in build
    # logs.  See also http://help.appveyor.com/discussions/problems/4569
    - del "C:\Program Files (x86)\MSBuild\12.0\Microsoft.Common.targets\ImportAfter\Xamarin.Common.targets"
    - ps: Start-FileDownload https://github.com/glfw/glfw/archive/3.2.1.zip -FileName glfw-3.2.1.zip
    - unzip glfw-3.2.1.zip
    - cd glfw-3.2.1
    - cmake -G "Visual Studio 12" -DBUILD_SHARED_LIBS=ON -DGLFW_BUILD_EXAMPLES=OFF -DGLFW_BUILD_TESTS=OFF -DGLFW_BUILD_DOCS=OFF .
    - cmake --build . --config Release --target install -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
    - cd ..
    build_script:
    - cmake -G "Visual Studio 12" -Dfreetype-gl_BUILD_APIDOC=OFF -Dfreetype-gl_BUILD_TESTS=OFF "-Dglfw3_DIR=C:/Program Files (x86)/GLFW/lib/cmake/glfw3" ..
    - cmake --build . --config RelWithDebInfo -- /logger:"C:\Program Files\AppVeyor\BuildAgent\Appveyor.MSBuildLogger.dll" /verbosity:minimal
    before_build:
    - if not exist build\NUL mkdir build
    - cd build
 
  -
    matrix:
      only:
        - job_group: MSVS
    
    build_script:
    - msbuild VisualC\freetype-gl.sln
